version: '3.8'

services:
  cyber-security-client:
    environment:
      - BASE_API_URL=http://localhost:8080
      - JWT_SECRET=secretkey123
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/src:/usr/src/app/src
    ports:
      - 3000:3000

  cyber-security-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/src:/usr/src/app/src
    ports:
      - 8080:8080